services:
  - type: web
    name: billing-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: PRODUCTION
        value: true
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: billing-db
    databaseName: billing
    user: billing_user
    plan: free